# Generated by Django 5.2.8 on 2026-01-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
