# Generated by Django 5.2.8 on 2026-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
